# https://taskfile.dev

version: '2'

vars:
  Product: 'ardan'

tasks:
  default:
    cmds:
      - echo "{{.Product}}"
      - task: run
    desc: default task
    silent: true
  
  run:
    desc: go run 
    deps: [res]
    cmds:
      - echo "go run"
      - go run main.go
    silent: true
  res:
    desc: embed files
    cmds:
      - echo "res generating..."
      - statik -src=./templates -include=*.*  -p=res -f
      - echo "res generated."
    silent: true

  release:
    desc: "release"
    deps: [res]
    cmds:
      - echo "release generating..."
      - go build -ldflags "-w -s" -o ./release/{{.Product}}_{{.GitCommit}} ./main.go
      - echo "release {{.Product}}_{{.GitCommit}}."
    vars:
      GitCommit:
        sh: git describe --always --tags --dirty
    silent: true

  version:
    desc: "version"
    cmds:
      - echo "current version:"
      - git describe --always --tags --dirty
    silent: true

