// Code generated by "stringer -type GenType -linecomment -output gen_type.go"; DO NOT EDIT.

package setting

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenTypeAll-0]
	_ = x[GenTypeQuery-1]
	_ = x[GenTypeRepository-2]
	_ = x[GenTypeServiceInterface-3]
	_ = x[GenTypeService-4]
	_ = x[GenTypeController-5]
}

const _GenType_name = "allqueryrepositoryservice interfaceservicecontroller"

var _GenType_index = [...]uint8{0, 3, 8, 18, 35, 42, 52}

func (i GenType) String() string {
	if i >= GenType(len(_GenType_index)-1) {
		return "GenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GenType_name[_GenType_index[i]:_GenType_index[i+1]]
}
